spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/resources
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true