server:
  port: 8080
spring:
  datasource:
    hikari:
      maximum-pool-size: 20
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop